CREATE DATABASE fusion;

CREATE TABLE clients (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE sections (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  client_id INT NOT NULL,
  FOREIGN KEY (client_id) REFERENCES clients (id)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);

CREATE TABLE links (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  section_id INT NOT NULL,
  FOREIGN KEY (section_id) REFERENCES sections (id)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);
